y=75
z=4
a=y+z
print("The value of ", y, "+", z, "=", a)
b=y-z
print("The value of ", y, "-", z, "=", b)
c=y*z
print("The value of ", y, "*", z, "=", c)
d=y/z
print("The value of ", y, "/", z, "=", d)